# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Update-DNT-With-Old-Master:
    if: ${{ github.ref == 'refs/heads/old-master' }}
    # The type of runner that the job will run on
    runs-on: [self-hosted, doc-build]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Build the full site
        run: |
          cd ${{ runner.temp }}
          mkdir -p DocHome
          git clone --depth 1 https://github.com/dynamsoft-docs/dotnet-twain-docs.git
          git clone --depth 1 --branch old-master https://github.com/dynamsoft-docs/Docs-Template-Repo.git
          cp -rfp ./dotnet-twain-docs/* ./DocHome/
          cp -rfp ./Docs-Template-Repo/* ./DocHome/
          cd DocHome && bundle install && bundle exec jekyll build
          # cd DocHome && bundle exec jekyll build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_DYNAMSOFT_LOCAL_SERVER }}
          username: ${{ secrets.FTP_DYNAMSOFT_LOCAL_USER }}
          password: ${{ secrets.FTP_DYNAMSOFT_LOCAL_PASSWORD }}
          port: 21 
          local-dir: ${{ runner.temp }}/DocHome/_site/
          server-dir: /www.dynamsoft.com/dotnet-twain/docs/

